module: PTVKit
module_version: 0.6.2

author: Matt Croxson
github_url: https://github.com/Lumus/PTVKit
copyright: © 2021 Matt Croxson

swift_version: 5.5.0
sdk: iphone os

output: ./docs
clean: true
readme: ./README.MD