module: PTVKit
module_version: 0.5.0

author: Matt Croxson
github_url: https://github.com/Lumus/PTVKit
copyright: © 2020 Matt Croxson

swift_version: 5.3.0
sdk: iphone os

output: ./docs
clean: true
readme: ./README.MD