module: PTVKit
module_version: 0.2.3

author: Matt Croxson
github_url: https://github.com/Lumus/PTVKit
copyright: © 2019 Matt Croxson

swift_version: 5.1.1
sdk: iphone os

output: ./docs
clean: true
readme: ./README.MD